import { ArrowRight, Minus, Plus, ShoppingBag, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { CakePhoto } from '../components/CakePhoto'
import { useCart } from '../context/CartContext'

export function Cart() {
  const { items, subtotal, updateQuantity, removeItem } = useCart()
  const delivery = items.length ? 79 : 0
  if (!items.length) return <main className='page-shell grid min-h-[68vh] place-items-center py-20 text-center'><div><span className='mx-auto grid size-20 place-items-center rounded-full bg-blush text-berry'><ShoppingBag size={34} /></span><h1 className='mt-6 font-display text-4xl font-semibold text-cocoa'>Your cart is waiting for something sweet 🍰</h1><p className='mt-3 text-stone-500'>A little celebration is only a few clicks away.</p><Link to='/cakes' className='btn-primary mt-7'>Explore cakes <ArrowRight size={18} /></Link></div></main>
  return <main className='page-shell py-12 sm:py-16'><p className='eyebrow'>Your selection</p><h1 className='mt-2 font-display text-5xl font-semibold text-cocoa'>Sweet things in your cart</h1>
      <div className='mt-10 grid items-start gap-8 lg:grid-cols-[1fr_380px]'><section className='grid gap-4'>{items.map((item) => <article key={item.cartId} className='grid grid-cols-[100px_1fr] gap-4 rounded-3xl border border-[#eadfd8] bg-white p-3 sm:grid-cols-[140px_1fr] sm:p-4'><CakePhoto index={item.imageIndex} collection={item.imageCollection} src={item.image} alt={item.name} className='aspect-square rounded-2xl' /><div className='flex min-w-0 flex-col justify-between py-1'><div className='flex justify-between gap-2'><div><h2 className='font-display text-xl font-semibold text-cocoa sm:text-2xl'>{item.name}</h2><p className='text-sm text-stone-500'>{item.size}{item.message && ' · “' + item.message + '”'}</p></div><button onClick={() => removeItem(item.cartId)} aria-label={'Remove ' + item.name} className='self-start p-2 text-stone-400 hover:text-berry'><Trash2 size={18} /></button></div>
      <div className='mt-3 flex items-center justify-between'><div className='flex items-center rounded-xl border border-[#dfd0c8]'><button className='p-2' onClick={() => updateQuantity(item.cartId, item.quantity - 1)} aria-label='Decrease quantity'><Minus size={15} /></button><strong className='w-7 text-center text-sm'>{item.quantity}</strong><button className='p-2' onClick={() => updateQuantity(item.cartId, item.quantity + 1)} aria-label='Increase quantity'><Plus size={15} /></button></div><strong className='text-berry'>₹{item.itemPrice * item.quantity}</strong></div></div></article>)}</section>
    <aside className='sticky top-28 rounded-[1.75rem] bg-cocoa p-6 text-white shadow-soft'><h2 className='font-display text-3xl font-semibold'>Order summary</h2><div className='mt-6 grid gap-3 border-b border-white/15 pb-5 text-sm'><p className='flex justify-between text-white/70'><span>Subtotal</span><span>₹{subtotal}</span></p><p className='flex justify-between text-white/70'><span>Delivery</span><span>₹{delivery}</span></p></div><p className='flex justify-between py-5 text-lg font-bold'><span>Total</span><span>₹{subtotal + delivery}</span></p><Link to='/checkout' className='btn-light w-full'>Proceed to checkout <ArrowRight size={18} /></Link><p className='mt-4 text-center text-xs text-white/45'>No payment required in this demo</p></aside></div>
  </main>
}
