import { Clock3, Send } from 'lucide-react'
import { useState } from 'react'
import { InstagramIcon } from '../components/InstagramIcon'

export function Contact() {
  const [sent, setSent] = useState(false)
  return <main className='page-shell py-14 sm:py-20'><div className='section-heading text-left'><p className='eyebrow'>Talk to us</p><h1>Let us make something lovely</h1><p>Planning a celebration or wondering which cake to choose? We would love to help.</p></div>
    <div className='grid gap-8 lg:grid-cols-[.8fr_1.2fr]'><aside className='rounded-[2rem] bg-cocoa p-7 text-white sm:p-9'><img src='/images/kash-crumbs-logo.png' alt='Kash & Crumbs' className='mb-5 h-24 w-24 rounded-full object-contain' /><h2 className='font-display text-3xl font-semibold'>Bakery details</h2><div className='mt-8 grid gap-6'>{[[InstagramIcon, 'Instagram', '@kash_crumbs'], [Clock3, 'Opening hours', 'Every day · 9:00 AM — 9:00 PM']].map(([Icon, label, value]) => <div key={label as string} className='flex gap-4'><span className='grid size-11 shrink-0 place-items-center rounded-xl bg-white/10 text-[#e8ad72]'><Icon size={20} /></span><div><p className='text-xs font-bold uppercase tracking-wider text-white/45'>{label as string}</p>{label === 'Instagram' ? <a href='https://www.instagram.com/kash_crumbs/' target='_blank' rel='noreferrer' className='mt-1 block text-sm transition hover:text-[#e8ad72]'>{value as string}</a> : <p className='mt-1 text-sm'>{value as string}</p>}</div></div>)}</div></aside>
    <form onSubmit={(event) => { event.preventDefault(); setSent(true) }} className='rounded-[2rem] border border-[#eadfd8] bg-white p-6 shadow-sm sm:p-9'><div className='grid gap-5 sm:grid-cols-2'><div><label className='field-label' htmlFor='name'>Your name</label><input className='field-input' id='name' required /></div><div><label className='field-label' htmlFor='phone'>Mobile number</label><input className='field-input' id='phone' type='tel' required /></div></div><div className='mt-5'><label className='field-label' htmlFor='email'>Email</label><input className='field-input' id='email' type='email' /></div><div className='mt-5'><label className='field-label' htmlFor='note'>How can we help?</label><textarea className='field-input min-h-32 resize-y' id='note' required /></div><button className='btn-primary mt-6' type='submit'><Send size={18} /> Send message</button>{sent && <p className='mt-4 rounded-xl bg-green-50 p-3 text-sm font-bold text-green-700'>Thanks! Your demo message has been received.</p>}</form></div>
  </main>
}
